### ISSUE TITLE
Add position prop

### ISSUE THREAD

**Issue by SamSamskies** [SamSamskies/react-map-gl-geocoder#10]
Allow user to pick which corner of the map to place the geocoder widget.

https://www.mapbox.com/mapbox-gl-js/api/#map#addcontrol

**Comment by AntwanSherif** [comment]
@SamSamskies Is there any way to set position to top-center?

**Comment by SamSamskies** [comment]
You'll need to place the geocoder component outside of the map using the `containerRef` prop. You'll have full control of the placement of the geocoder using CSS by doing this.
