### ISSUE TITLE
GeoCoder Marker's Styling Not Working 

### ISSUE THREAD

**Issue by MuhammadJafarFA17BCS054** [SamSamskies/react-map-gl-geocoder#100]
Hi, 
I have been trying for a few days now to solve an issue that I have had and is very irritating. I am simply trying to apply custom styling to the marker that is dropped by GeoCoder, but whenever i pass anything else (except true) to "marker" prop, the marker stops showing on map, and the geocoder results do not hide on click. Can someone help me? 
![image](https://user-images.githubusercontent.com/76398215/108421343-e0405b00-7256-11eb-9579-ef9382f448bc.png)

**Comment by SamSamskies** [comment]
Hi @MuhammadJafarFA17BCS054, you have to make sure to memoize any props that are objects or functions. Is `MARKER_OPTIONS` defined outside of your function? If not, you need to memoize it.

**Comment by MuhammadJafarFA17BCS054** [comment]
@SamSamskies Thank you so much man!! I defined the MARKER_OPTIONS outside my function and it worked like a charm.
![image](https://user-images.githubusercontent.com/76398215/108423270-78d7da80-7259-11eb-8d74-7dff3db0463a.png)
