### ISSUE TITLE
Return GeoCoded Latitude  Longitude  Results only

### ISSUE THREAD

**Issue by hellofantastic** [SamSamskies/react-map-gl-geocoder#12]
Instead of having a search box can I feed in an address from dataset and get back Lat and Long to use in Mapbox?

**Comment by hellofantastic** [comment]
Hmm Looking at your code that includes  @mapbox/mapbox-gl-geocoder  thats what I want to use....

**Comment by SamSamskies** [comment]
Yeah, but I've never used it directly so I'm not sure how it is. https://www.mapbox.com/help/how-geocoding-works/

Another alternative geocoding API you could check out is from HERE Technologies (I work here). https://developer.here.com/documentation/geocoder/topics/what-is.html

**Comment by hellofantastic** [comment]
Oh thanks for responding @SamSamskies... i ended up grabbing the @mapbox/mapbox-gl-geocoder package and making a GET request to the mapbox API (https://api.mapbox.com/geocoding/v5/mapbox.places/Los%20Angeles.json?access_token=your-access-token)  where Los Angeles can be any full address url encoded
