### ISSUE TITLE
viewport-mercator-project: assertion failed.

### ISSUE THREAD

**Issue by jlubeck** [SamSamskies/react-map-gl-geocoder#13]
After click on a result from the geocoder, I'm getting this error:

```
assert.js:3 Uncaught Error: viewport-mercator-project: assertion failed.
    at assert (assert.js:3)
    at pixelsToWorld (web-mercator-utils.js:194)
    at WebMercatorViewport.unproject (viewport.js:102)
    at InteractiveMap._onMouseClick (interactive-map.js:265)
    at Array.<anonymous> (event-manager.js:360)
    at Manager.emit (hammer.js:2525)
    at TapRecognizer.emit (hammer.js:2130)
    at TapRecognizer.tryEmit (hammer.js:1572)
    at TapRecognizer.<anonymous> (hammer.js:2109)
    at boundFn (hammer.js:197)
```

And the whole screen is turning white.

**Comment by Lndubose** [comment]
That is because your latitude and longitude are incorrect. So it is not a real place you have set.

**Comment by SamSamskies** [comment]
@jlubeck could you provide more info so that I can try to replicate this issue? Some things that may help is your search query that is causing it to crash, what browser you are using, etc. If you could provide an example using an online code editor like Code Sandbox http://codesandbox.io, that would be even more helpful.

**Comment by jlubeck** [comment]
Ok, this is weird...

Here is my code: https://codesandbox.io/s/7v21m7yxq

That exact code works on codesandbox but not on my site...

Any ideas how can I get to the bottom of this?

**Comment by jlubeck** [comment]
Ok... progress... I figured out why it was crashing. When clicking on one of the results, the onClick event from the Map was being called as well but without coordinates. Why without coordinates? Because the map is disappearing after selecting a result. 

The DOM for the Map is still there, but the style has a width and height of 0px. So strange.... Specially that it doesn't happen on the codesandbox

**Comment by SamSamskies** [comment]
I can look into stopping the result click from bubbling up to the map, but I'm not sure when I'll get around to it.

For now, I don't see a downside to checking if the coordinates exist in your click handler. I'm guessing that will fix your problem.

**Comment by jlubeck** [comment]
The downside is that my map is turning blank :D 
I already tried removing the click handler altogether, and the map is turning blank after selecting a result from the Geocoder

**Comment by jlubeck** [comment]
BTW, thank you for responding so quickly!

**Comment by SamSamskies** [comment]
When I go to your Code Sandbox example, the map is blank before I even enter a search query. There may be a bug with your state management. It's even blank if I remove the Geocoder component. The state of your Map component is intermittently undefined when I console log it in the render function.

**Comment by jlubeck** [comment]
That's weird. I don't see it blank and I see the logs on the render function just fine:
![7v21m7yxq - codesandbox 2018-12-03 14-53-37](https://user-images.githubusercontent.com/3067603/49398062-46d70e00-f70b-11e8-8be6-37d32c95e5ec.png)

**Comment by jlubeck** [comment]
Good news is that your demo code works fine on my environment... so I guess I'll start replacing stuff line by line until I find the culprit...

I'll let you know what I find, and thanks again for your help

**Comment by SamSamskies** [comment]
Disregard my comment about the state being undefined intermittently in your Code Sandbox example. It was actually a console.log that was in the componentDidUpdate function that was printing undefined. I got the map the show up by removing your mapStyle. Maybe I don't have permissions to access the mapStyle that you're using.

**Comment by jlubeck** [comment]
Well... you can mark this one as glitch... no other words for it... I started with your example code. Replacing line by line. I finished... Everything is working fine... Don't know wether to be happy or outraged haha

Sorry for wasting your time. Looks like a great library! I'll make sure to double check more thoroughly next time. 

Thanks!

**Comment by SamSamskies** [comment]
No problem. Let me know if any issues pop up.
