### ISSUE TITLE
Is it possible to hide/show the component?

### ISSUE THREAD

**Issue by jlubeck** [SamSamskies/react-map-gl-geocoder#14]
Please check this out: https://codesandbox.io/s/2oml8ypklp

Try clicking once on the map. You will see the geocoder. Click again. nothing happens (it should hide)
Click again, a second geocoder appears.

And like that forever

Thanks!

**Comment by SamSamskies** [comment]
That's a bug. I'll push a fix in a lil bit.

**Comment by SamSamskies** [comment]
It actually might take longer to fix. Clicking in the Geocoder input now makes it disappear because that click bubbles up to the map which toggles the showGeocoder flag in your case.

**Comment by jlubeck** [comment]
Clicking on the map was just a quick example to show the bug. Although it would be a nice to have, i dont think its critical...

**Comment by SamSamskies** [comment]
I just pushed a fix so that it properly cleans up the Mapbox geocoder when unmounting.

**Comment by jlubeck** [comment]
Works great! Thanks!
