### ISSUE TITLE
Example not working with react-map-gl v4.0.5

### ISSUE THREAD

**Issue by vnugent** [SamSamskies/react-map-gl-geocoder#17]
Thanks for providing this wrapper.
I updated packages in the codesandbox example and it's not running any more.

```
    "deck.gl": "6.3.2",
    "react-map-gl": "4.0.5",
    "react-map-gl-geocoder": "1.5.6",
```

https://codesandbox.io/s/vj180v0vjl

![image](https://user-images.githubusercontent.com/3805254/50016514-44cc4500-ff7e-11e8-92a6-1a8e250f3702.png)

**Comment by SamSamskies** [comment]
I removed react-map-gl-geocoder from your sandbox and it still has the same error. It might be an issue with Code Sandbox. I'll try it locally to see what happens.

**Comment by SamSamskies** [comment]
I downloaded the sandbox and it works locally, so must be an issue with Code Sandbox. Let me know if you have any other problems.

**Comment by SamSamskies** [comment]
I filed an issue with Code Sandbox https://github.com/CompuIves/codesandbox-client/issues/1381
