### ISSUE TITLE
Can't resolve 'gl-mat4/invert'

### ISSUE THREAD

**Issue by Sela1236** [SamSamskies/react-map-gl-geocoder#23]
i updated packages and now i get this error

Failed to compile.
./node_modules/react-map-gl-geocoder/node_modules/viewport-mercator-project/dist/esm/viewport.js
Module not found: Can't resolve 'gl-mat4/invert' in '...'

react: 16.8.1,
deck.gl: 6.4.1,
react-map-gl: 4.0.10,
react-map-gl-geocode": 1.6.3,

**Comment by SamSamskies** [comment]
I upgraded the viewport-mercator-project dependency and this seems to have fixed the issue. They got rid of the the dependency that was causing this issue.

Let me know if you have any problems with v1.6.4.
