### ISSUE TITLE
Filtering suggestions further to trim results to a city

### ISSUE THREAD

**Issue by sabib0y** [SamSamskies/react-map-gl-geocoder#39]
This is probably a noob question on my part so apologies in advance.
I am currently trying to add geo-filtering to my map to lock things down to a city but search suggestions still show areas outside the target zone which tells me I'm probably doing something wrong.

Here's my code:

        <MapGL
            ref={this.mapRef}
            {...viewport}
            onViewportChange={this.handleViewportChange}
            mapboxApiAccessToken={MAPBOX_TOKEN}
        >
          <Geocoder
              mapRef={this.mapRef}
              onResult={this.handleOnResult}
              containerRef={this.geocoderContainerRef}
              onViewportChange={this.handleGeocoderViewportChange}
              mapboxApiAccessToken={MAPBOX_TOKEN}
              reverseGeocode={true}
              bbox={[-0.489,51.28,0.236,51.686]}
              filter={event => {
                // returns true if item contains New South Wales region
                return event.context.map( i => {
                  return (i.id.split('.').shift() === 'place' && i.text === 'London');
                }).reduce(function (acc, cur) {
                  return acc || cur;
                });;
              }}
          />
          <DeckGL {...viewport} layers={[searchResultLayer]} />
        </MapGL>

I guess the question here would be; what should go in the reduce function arguments?

**Comment by SamSamskies** [comment]
Hi @sabib0y, thanks for raising the issue. I'll look into this tonight.

**Comment by SamSamskies** [comment]
You don't need the `filter` prop if you have the bounding box of the area that you are interested in. You can just use the `bbox` prop. Please see this example https://codesandbox.io/s/reactmapglgeocoder-bbox-example-zzlf1.

As for using the `filter` prop for filtering results, the function receives a single result in [Carmen GeoJSON](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md) format. You can parse that result and return `true` or `false` depending on if you'd like to include that result in the suggestions shown.

Let me know if you have any questions or need any more help.

**Comment by SamSamskies** [comment]
Let me know if you'd like me to provide an example of using the `filter` prop as well.

**Comment by SamSamskies** [comment]
@sabib0y also whipped up a `filter` example for you https://codesandbox.io/s/reactmapglgeocoder-filter-example-602xq
