### ISSUE TITLE
MapGL viewport does not update when location changed with geocoder

### ISSUE THREAD

**Issue by jaronheard** [SamSamskies/react-map-gl-geocoder#4]
In your example code, the MapGL viewport state does not update when a location is changed in the geocoder, and I don't think there is an easy way to do it with your module as structured.

When the location is updated from the geocoder, the state of the MapGL component will not be up to date with the map, and if you're doing anything else that relies on the viewport (e.g. Deck.GL layers), you'll have issues.

NavigationControl in react-map-gl implements an onViewportChange prop, which I think is a pattern that could be implemented here.
https://github.com/uber/react-map-gl/blob/master/src/components/navigation-control.js

This forked sandbox logs viewport adds NavigationControl showing use of the onViewportChange prop and logs viewport to the console.
https://codesandbox.io/s/1zk0wz3n87

I could work up a PR if you'd prefer.

**Comment by SamSamskies** [comment]
Thanks for reporting these bugs. I'm probably not going to have time to fix this tonight, so feel free to have a go at it.

**Comment by SamSamskies** [comment]
You could probably listen for the zoomend event and update the lat, lng, and zoom of the viewport then.

**Comment by jaronheard** [comment]
Spent a little more time looking at this, and the implementation of the onViewportChange in NavigationControl was significantly more involved than I thought it was going to be. Listening for zoomend sounds promising, but not sure on implementation details for that.

**Comment by SamSamskies** [comment]
The results and result event from mapbox-gl-geocoder might also be worth looking into.
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md

Here's the docs for the zoomend mapbox-gl map event.
https://www.mapbox.com/mapbox-gl-js/api/#map.event:zoomend

I think we may need to get rid of the the animation transition to get this to work. I'm not sure how we'd animate deck.gl layers along with the base map.

If I get a second wind later tonight, I'll have a crack at it.

**Comment by SamSamskies** [comment]
Should be fixed now. The zooming can be improved to zoom in on the bounding box of the area that is searched for. I'll add that later.

Let me know if you have any problems.

**Comment by jaronheard** [comment]
Cheers, thanks for this! Works great with deck.gl layers now, including during animation.
