### ISSUE TITLE
Error: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by leizleho** [SamSamskies/react-map-gl-geocoder#40]
Hi, when running your codesandbox, console shows error 422 (unprocessable entity).

**Comment by SamSamskies** [comment]
Hi @leizleho, I'm not seeing the error. Is this (https://codesandbox.io/s/l7p179qr6m) the sandbox that you're seeing the error in? If it is, what browser are you using?

**Comment by leizleho** [comment]
Yeah, this one https://codesandbox.io/s/react-map-gl-geocoder-v2-example-74mcp and this one https://codesandbox.io/s/l7p179qr6m.
The  console error shows when you enter a place in the search box. I am using chrome developer tools. 

This is the console error:
POST https://api.mapbox.com/events/v2?access_token=pk.eyJ1Ijoic21peWFrYXdhIiwiYSI6ImNqcGM0d3U4bTB6dWwzcW04ZHRsbHl0ZWoifQ.X9cvdajtPbs9JDMG-CMDsA 422 (Unprocessable Entity)

**Comment by SamSamskies** [comment]
Ah, I see what you mean. I think you can just ignore that error. The Mapbox API seems to return a 422 occasionally while typing. If that error is causing you problems with the geocoder, let me know what search queries are causing you problems.
