### ISSUE TITLE
how to provide inputValue and perform search

### ISSUE THREAD

**Issue by vnugent** [SamSamskies/react-map-gl-geocoder#42]
When I provide an `inputValue` the value is simply displayed in the box but no search is done.  How do you also tell the geocoder to also do the search?

**Comment by SamSamskies** [comment]
You can't unless you get a handle to Mapbox gecoder object using the onInit prop. I do not recommend performing imperative actions on the geocoder object though. You could get yourself into an infinite rendering loop if you're not careful.

I suggest hitting the Mapbox Geocoding API directly to perform your search. https://docs.mapbox.com/api/search/
