### ISSUE TITLE
Improvement - Map reference

### ISSUE THREAD

**Issue by marek-sed** [SamSamskies/react-map-gl-geocoder#48]
You might not need a map when you are not using flyTo from mapbox gl.

**Comment by SamSamskies** [comment]
Hi @marek-sed, without the map, nothing will work. This component performs imperative actions using the map. That's why the render function returns null. https://github.com/SamSamskies/react-map-gl-geocoder/blob/master/src/index.js#L230

**Comment by marek-sed** [comment]
copied your geocoder to our project, everything works ;)

**Comment by SamSamskies** [comment]
The imperative actions I was talking about are the Mapbox map imperative actions such as `addControl` https://github.com/SamSamskies/react-map-gl-geocoder/blob/master/src/index.js#L93.

When I first started this project, I didn't know you could add the `@mapbox/mapbox-gl-geocoder` object by appending it to an outside HTML node. I didn't discover this until later when someone raised an issue that they'd like to place the geocoder outside of the map.

At this point, I think most people use this component without the containerRef and I believe the changes that you suggest would require it. 

Let me know if you decide to open source your more composable solution and I'll add a link in the README.

**Comment by marek-sed** [comment]
Yeah was thinking about a bit it seems like a new component now.
Will try to opensource it after I have some more time.

btw thank you for making this library its 💯
