### ISSUE TITLE
Zoom to bounding box when possible on geocode autocompletion

### ISSUE THREAD

**Issue by SamSamskies** [SamSamskies/react-map-gl-geocoder#5]

**Comment by jaronheard** [comment]
If no bounding box is found, it would be nice if it used the "options.zoom" property of the geocoder to choose the zoom level if one was provided.

Per [mapbox-gl-geocoder docs](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md):
    -   `options.zoom` **[Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)** On geocoded result what zoom level should the map animate to when a `bbox` isn't found in the response. If a `bbox` is found the map will fit to the `bbox`. (optional, default `16`)

**Comment by SamSamskies** [comment]
@jaronheard how important is this feature for you? Got a lot on my plate this week, but I can bump the priority on this if it's critical for you.

**Comment by jaronheard** [comment]
This isn't urgently critical, it's more of a nice to have. Thanks again for
your work on this!

**Comment by SamSamskies** [comment]
@jaronheard I finally got around to implementing this. Check out v1.3.2 and let me know if you have any problems.
