### ISSUE TITLE
Could not find declaration for module

### ISSUE THREAD

**Issue by mohridwanhdp** [SamSamskies/react-map-gl-geocoder#50]
I can't run my app because the import proccess always says 
"Could not find a declaration file for module 'react-map-gl-geocoder'. '/..../app-map/node_modules/react-map-gl-geocoder/dist/index.js' implicitly has an 'any' type."

Can you help me how to fix it?

I had install the react-map-gl-geocoder

![line_20190909_174732](https://user-images.githubusercontent.com/26524489/64524978-f3dd5780-d329-11e9-8aca-59a9cb8916bf.png)

**Comment by SamSamskies** [comment]
Seems like you're using Typescript. Currently, there are no published types for this lib. You can use shorthand declaration to explicitly define this module as an 'any' type. https://www.typescriptlang.org/docs/handbook/modules.html#shorthand-ambient-modules

**Comment by mikiyasgirma** [comment]
×
TypeError: i._requestDomTask is not a function

Hey Sam, This is what I am getting when I selected the results from the recommendation. Please help me with what shall I do. Thank you in advance
