### ISSUE TITLE
queryParams prop seems ignored

### ISSUE THREAD

**Issue by adesurirey** [SamSamskies/react-map-gl-geocoder#51]
Hello and thanks for this nice library! 
I'm passing a `queryParams` prop to geocoder but it doesn't change the request. Am I doing it wrong?

```js
const bbox = {
  ne: { lng: -34.31067179238596, lat: 46.03500843336249 },
  sw: { lng: -113.41223429238529, lat: -9.32997469975038 },
};

const center = {
  latitude: 20.827873989993776,
  longitude: -73.86145304236818,
};

const queryParams = {
  bbox: [bbox.sw.lng, bbox.sw.lat, bbox.ne.lng, bbox.sw.lng],
  proximity: [center.longitude, center.latitude],
};
```

```js
<Geocoder
  mapboxApiAccessToken={mapboxApiAccessToken}
  mapRef={this.mapRef}
  containerRef={this.geocoderContainerRef}
  queryParams={queryParams}
  clearAndBlurOnEsc
  onViewportChange={this.onViewportChange}
/>
```

Result in network console stays the same and does not include my params:
```
https://api.mapbox.com/geocoding/v5/mapbox.places/me.json?limit=5&language=fr-FR&access_token=[secret]
```

**Comment by SamSamskies** [comment]
Hi @adesurirey, there is no queryParams prop. Did you see that in an example somewhere?

Check the [README](https://github.com/SamSamskies/react-map-gl-geocoder) for supported props. Here's a bbox example https://codesandbox.io/s/zzlf1. For your `proximity` prop, I think you can pass in your `center` object.

**Comment by adesurirey** [comment]
Well your right, I was on the mapbox-gl-geocoder readme... 🤦‍♂️Thanks for your answer.
