### ISSUE TITLE
Cursor interacts with map through the geocoder control

### ISSUE THREAD

**Issue by mddilley** [SamSamskies/react-map-gl-geocoder#53]
When hovering the cursor over the geocoder control, clicking and dragging with the cursor moves the map below. The map also zooms when double-clicking over the search bar (see below). This can cause issue when drag-selecting the string in the control.

The issue is replicated in the demo in this repo (https://codesandbox.io/s/l7p179qr6m).

Does anyone have a workaround for this? I've tried modifying the z-index so far with no luck.  

![64724987-340f1800-d499-11e9-94a7-d48de099ba7f](https://user-images.githubusercontent.com/37249039/65619727-42bff980-df86-11e9-93ed-073757273b59.gif)

Thanks @SamSamskies for this great library!

**Comment by SamSamskies** [comment]
Hi @mddilley, `react-map-gl` places a map overlay to capture events. To avoid this you could place the geocoder outside of the map using the `containerRef` prop https://codesandbox.io/s/v0m14q5rly. Or you use a custom `MapController` to capture the events https://codesandbox.io/s/react-map-gl-geocoder-ignore-events-example-x652y.

**Comment by mddilley** [comment]
@SamSamskies - this is amazing. Thanks so much for steering me in the right direction and providing the code examples. This is extremely helpful in getting it right for our users. I like the custom `MapController` route, and I'll be implementing asap.
