### ISSUE TITLE
reverseGeocode not working

### ISSUE THREAD

**Issue by Mrebai** [SamSamskies/react-map-gl-geocoder#55]
I'm trying to display the address of the location on click but it's not showing in the geocoder.

```
 <MapGl
      {...viewport}
      ref={mapRef}
      mapboxApiAccessToken={token}
      onViewportChange={viewState => setViewport(viewState)}
      transitionInterpolator={new FlyToInterpolator()}
      onClick={e => {
         handleGeocoderViewportChange({ latitude: e.lngLat[1], longitude: e.lngLat[0] });
    >
      <Geocoder
        mapRef={mapRef}
        mapboxApiAccessToken={token}
        onViewportChange={handleGeocoderViewportChange}
        proximity={{ ...viewport }}
        trackProximity
        reverseGeocode
      />
  </MapGl>
```

**Comment by SamSamskies** [comment]
Hi @Mrebai, you can't programmatically execute a reverse geocode query like this with this component. I'd suggest hitting the Mapbox API directly on click and then updating your viewport using the response. https://docs.mapbox.com/api/search/#reverse-geocoding

**Comment by SamSamskies** [comment]
And if you want to update the geocoder input value with the response, you can use the `inputValue` prop to do that.

**Comment by ncesar** [comment]
if anyone comes across this problem, use the search playgrounds, things get way easier with this.
https://docs.mapbox.com/search-playground
