### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by SamSamskies** [SamSamskies/react-map-gl-geocoder#58]
**Demo section**
- include demo that is a functional component and uses hooks
- include code that demos how to ignore map events in the linked Code Sandboxes

**Example code displayed**

- switch to a functional component that uses hooks.
- includes code that demos how to ignore map events

**Comment by AntwanSherif** [comment]
I also would like to know how to style the geocoder search input to look as my custom input component

**Comment by SamSamskies** [comment]
Hi @AntwanSherif, you can override the `@mapbox/mapbox-gl-geocoder` CSS styles https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.2.0/mapbox-gl-geocoder.css. One problem with that is if `@mapbox/mapbox-gl-geocoder` ever changes the class names and I upgrade to that version, your overrides will break.
