### ISSUE TITLE
how to use only the Geocoder and not the map

### ISSUE THREAD

**Issue by heshamelmasry77** [SamSamskies/react-map-gl-geocoder#61]
I tried to use only the Geocoder so i can only get the lat and lng. it does work but i have some issue regarding a container 
<img width="1016" alt="Screenshot 2020-01-22 at 13 02 51" src="https://user-images.githubusercontent.com/15607302/72889070-8e599880-3d17-11ea-9509-c29034cedbc9.png">

i did that :

```
<div>
        <div
          ref={this.geocoderContainerRef}
          style={{
            height: 50,
            background: "black",
            display: "flex",
            alignItems: "center",
            paddingLeft: 4
          }}
        />

        <Geocoder
          mapRef={this.mapRef}
          containerRef={this.geocoderContainerRef}
          onResult={this.handleOnResult}
          onViewportChange={this.handleGeocoderViewportChange}
          mapboxApiAccessToken={MAPBOX_TOKEN}
        />
        <DeckGL {...viewport} layers={[searchResultLayer]} />
      </div>
```

**Comment by SamSamskies** [comment]
Hi @heshamelmasry77, is it possible to post the code for the whole component? It would be even better if you could put it in a Code Sandbox and link the sandbox.

**Comment by SamSamskies** [comment]
Also, are you trying to use this component without the `react-map-gl` map? Because if you are, that's not possible. If all you want to do is geocoding, you can hit the Mapbox API directly. https://docs.mapbox.com/api/search/

**Comment by heshamelmasry77** [comment]
@SamSamskies Hey :) yeah i actually wanted to use the search stand alone i constructed my search bar. I will post it here once i finish it. Thank you a lot. you may close this issue.

**Comment by AntwanSherif** [comment]
Hi @SamSamskies,

I want to place the geocoder outside the map, but instead of adding the geocoder ref to a div, I want to customize it/use it as one of my components.

It's a nice idea  to use the APIs directly but it's a lot of work and re-implementation of the logic provided by your library

**Comment by micahmones** [comment]
@SamSamskies @AntwanSherif  did either of you have a solution ?
