### ISSUE TITLE
Type issue while onHover and onClick triggers.

### ISSUE THREAD

**Issue by I1mran** [SamSamskies/react-map-gl-geocoder#63]
Hello, I am facing the issue of gl geocoder disable after adding to clicks popup on MapGL instance, on hover, and onClick popup
Let me know how I can resolve this.

**Comment by SamSamskies** [comment]
Hi @I1mran, is it possible for you to provide a Code Sandbox (https://codesandbox.io/) that demonstrates this issue?

**Comment by I1mran** [comment]
I don't have code right now for sharing.
