### ISSUE TITLE
Paste on Mac doesn't run the query

### ISSUE THREAD

**Issue by yurivangeffen** [SamSamskies/react-map-gl-geocoder#66]
Pasting (Cmd+V) on Mac doesn't run the query like it does on other platforms or when typing.
This should be fixed in v4.5.0 of the underlying package: https://github.com/mapbox/mapbox-gl-geocoder/issues/140. However, manually upgrading mapbox-gl-geocoder to v4.5.0 doesn't seem to fix it.

The following is a non-ideal workaround:

```typescript
<Geocoder
...
onInit={(par: any) => {
  const inputField = par.container.querySelector('input.mapboxgl-ctrl-geocoder--input');

  if (!inputField) return

  inputField.addEventListener('paste', (event:any) => {
      //@ts-ignore
      const text = (event.clipboardData || window.clipboardData).getData('text');
      if (text && text.length > 2) {
          par.query(text);
      }
  });
}}/>
```

**Comment by SamSamskies** [comment]
Hey @yurivangeffen, thanks for raising this issue. It should be fixed in the latest release which is v2.0.14.
