### ISSUE TITLE
Marker prop is absent in the wrapper

### ISSUE THREAD

**Issue by neeleshbisht99** [SamSamskies/react-map-gl-geocoder#69]
Marker prop is absent I guess , which needs to be added

**Comment by SamSamskies** [comment]
Hi @neeleshbisht99, `marker` prop has been added and it defaults to `true` which is the currently the same behavior as `mapbox-gl-geocoder`. https://github.com/SamSamskies/react-map-gl-geocoder/releases/tag/v2.1.0
