### ISSUE TITLE
Demo doesn't load - returns error

### ISSUE THREAD

**Issue by andrewshrout** [SamSamskies/react-map-gl-geocoder#71]
`SyntaxError
Invalid left-hand side expression in prefix operation
xo
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:199475
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216433
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:239498
t
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216129
    at evaluate (https://l7p179qr6m.csb.app/node_modules/
deck.gl/geo-layers/dist/esm/h3-layers/h3-cluster-layer.js:22:18
xo
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:199479
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216433
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:239498
t
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216129
    at evaluate (https://l7p179qr6m.csb.app/node_modules/
deck.gl/geo-layers/dist/esm/index.js:37:57
xo
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:199479
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216433
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:239498
t
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216129
evaluate
https://l7p179qr6m.csb.app/node_modules/deck.gl/dist/esm/index.js:428:23
xo
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:199479
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216433
e.value
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:239498
t
https://codesandbox.io/static/js/sandbox.9bb533ef6.js:1:216129
evaluate
/src/index.js:6
  3 | import React, { Component } from "react";
  4 | import { render } from "react-dom";
  5 | import MapGL from "react-map-gl";
> 6 | import DeckGL, { GeoJsonLayer } from "deck.gl";
  7 | import Geocoder from "react-map-gl-geocoder";
  8 | 
  9 | // Please be a decent human and don't abuse my Mapbox API token.
View compiled
▶ 10 stack frames were collapsed.
`

Trying to mess around with the demo because I'm looking to add a search function to my map, but the demo doesn't load.

**Comment by SamSamskies** [comment]
Hey @andrewshrout, thanks for raising the issue. Seems to be a problem with Code Sandbox. It seems like none of the sandboxes using deck.gl are working at the moment. I removed deck.gl from the demo which fixed the problem. https://codesandbox.io/s/l7p179qr6m
