### ISSUE TITLE
Option to add control that gets a user's location?

### ISSUE THREAD

**Issue by josephfusco** [SamSamskies/react-map-gl-geocoder#74]
Thank you for your work on the project, it has been a pleasure using this package.

I was curious what the recommended way would be to display a 'locate user' button that gets the user's current location and automatically fills the geocoder input with that value? Similar to the locate user example in mapbox's docs: https://docs.mapbox.com/mapbox-gl-js/example/locate-user/

**Comment by SamSamskies** [comment]
Hi @josephfusco, I think that should be implemented as a separate component. It looks like `react-map-gl` actually provides a `GeolocateControl` component http://visgl.github.io/react-map-gl/docs/api-reference/geolocate-control.

**Comment by SamSamskies** [comment]
Looks like you could use the `onGeolocate` prop for the `GeolocateControl` in combination with the `inputValue` prop of this component to accomplish what you're trying to do.

**Comment by josephfusco** [comment]
Thank you @SamSamskies!
