### ISSUE TITLE
Cannot Add Custom CSS

### ISSUE THREAD

**Issue by rachelombok** [SamSamskies/react-map-gl-geocoder#75]
Hello, I had a question about adding CSS, since I could not find any other issues related to this. I am trying to move the Geocoder Search farther down the map than where it is positioned at 'top-right' and I cannot change it's position, whether I use inline or internal CSS:

```
import React from "react";
import "mapbox-gl/dist/mapbox-gl.css";
import "react-map-gl-geocoder/dist/mapbox-gl-geocoder.css";
import Geocoder from "react-map-gl-geocoder";
const geostyle {
    margin: '20px';
}

const Map = () = > {`
...
return(
<div>
...
<Geocoder
    style={geostyle}
    mapRef={myMap}
    onViewportChange={setViewport}
    mapboxApiAccessToken={MAPBOX_TOKEN}
    viewport={viewport}
    position="top-left"
  />
...
</div>
);
};

```

Is there a way to customize the Geocoder search bar? Would I have to edit the mapbox-gl-geocoder.css file? I assume that's not reccomended.

**Comment by SamSamskies** [comment]
Hi @rachelombok, check out the `containerRef` prop which gives you more control on where to place the component. Here's an example: https://codesandbox.io/s/v0m14q5rly.

**Comment by SamSamskies** [comment]
If you want to customize the how the options are rendered, you and can use the render prop. If you need more customization than that, I would suggest building your own Geocoder component using the Mapbox geocoding API directly.

**Comment by rachelombok** [comment]
Thank you that worked!

**Comment by rachelombok** [comment]
Thank you that worked!
