### ISSUE TITLE
How to replace left side search icon with my custom icon?

### ISSUE THREAD

**Issue by debotos** [SamSamskies/react-map-gl-geocoder#77]
<img width="232" alt="Screenshot 2020-09-01 at 9 07 57 PM" src="https://user-images.githubusercontent.com/29367677/91869259-7c6daa00-ec97-11ea-92fb-a1953b9f94d4.png">

**Comment by SamSamskies** [comment]
Hi @debotos, this component is pretty much just a wrapper around `mapbox-gl-geocoder` and unfortunately I don't think there's a nice way to do that with the `mapbox-gl-geocoder` API. As a hack, you could use CSS to absolutely position your icon over the default icon.

**Comment by debotos** [comment]
Hey @SamSamskies, Thanks.
