### ISSUE TITLE
reverse Geocode

### ISSUE THREAD

**Issue by dinaandrei** [SamSamskies/react-map-gl-geocoder#79]
Hello, i do not quite understand from the documentation how to get a location based on the latLong. How do you pass that information?

**Comment by SamSamskies** [comment]
Hi @dinaandrei, here's an example of how to use the `reverseGeocode` prop https://codesandbox.io/s/react-map-gl-geocoder-reversegeocode-example-d7rtm.

![reverse-geocode-example](https://user-images.githubusercontent.com/3655410/96081573-6c3c1380-0e6e-11eb-8b8a-90945e1cd786.gif)
