### ISSUE TITLE
Animation speed settings

### ISSUE THREAD

**Issue by sos0** [SamSamskies/react-map-gl-geocoder#8]
Hi @SamSamskies,
I just integrated this into my project and noticed that the animation is very slow when updating location. Is there a way to change the settings to update this? Thanks for your hard work!

**Comment by SamSamskies** [comment]
Hi @sos0 ,
Currently, it's not possible to change the speed of the animation. I can work on adding that this weekend. For now you could disable the animation by passing in options with flyTo set to false.

```jsx
<Geocoder options={{ flyTo: false }} mapRef={this.mapRef} onViewportChange={this._onViewportChange} mapboxApiAccessToken={MAPBOX_TOKEN} />
```

I haven't documented it, but any options you pass to the component are used to instantiate the mapbox-gl-geocoder instance. I'll work on adding this information to the docs as well.

mapbox-gl-geocoder API:
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md

Thanks for filing the issues 😄

**Comment by SamSamskies** [comment]
I looked into this more and the map is the one that should be dictating the speed of the animation by setting the transitionDuration prop on the React MapGL element. I will be removing the default animation in the next release. For now, you can work around my mistake by setting the transitionInterpolator and transitionDuration AFTER spreading this.state.viewport as in the example below. Once I remove the default animation that I forced by passing the transitionInterpolator and transitionDuration to onViewportChange, the order of the of the transitionInterpolator and transitionDuration props on MapGL won't matter.

```jsx
<MapGL
  ref={this.mapRef}
  {...this.state.viewport}
  transitionInterpolator={new FlyToInterpolator()}
  transitionDuration={3000}
  onViewportChange={this._onViewportChange}
  mapboxApiAccessToken={MAPBOX_TOKEN}>
  <Geocoder mapRef={this.mapRef} onViewportChange={this._onViewportChange} mapboxApiAccessToken={MAPBOX_TOKEN} />
</MapGL>
```

The FlyToInterpolator can be imported from react-map-gl.

```javascript
import MapGL, { FlyToInterpolator } from 'react-map-gl'
```

**Comment by SamSamskies** [comment]
Actually, I'm going to leave the default animation in as long as flyTo option is not set to false. I'll update the example in the README with a better way to override the transitionDuration.

**Comment by SamSamskies** [comment]
> ```js-jsx
> <Geocoder options={{ flyTo: false }} mapRef={this.mapRef} onViewportChange={this._onViewportChange} mapboxApiAccessToken={MAPBOX_TOKEN} />
> ```
> 
> I haven't documented it, but any options you pass to the component are used to instantiate the mapbox-gl-geocoder instance. I'll work on adding this information to the docs as well.
> 
> mapbox-gl-geocoder API:
> https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md

I'm think I'm going to change this. I was just being lazy. Probably going to make each option a prop instead of passing down a whole options object.

**Comment by SamSamskies** [comment]
Updated my example to show how to override the default animation speed. https://codesandbox.io/s/vv29y730q3

**Comment by sos0** [comment]
Thanks! I'll look into this now and ask any follow up questions if I have any.

**Comment by sos0** [comment]
I followed your example and it worked great! Thank you.
