### ISSUE TITLE
When using containerRef input options do not collapse

### ISSUE THREAD

**Issue by nerijusgood** [SamSamskies/react-map-gl-geocoder#84]
- or add possibility to control select dropdown/suggestion list.

If necessary i can try re-create issue.

**Comment by SamSamskies** [comment]
Hi @nerijusgood, make sure that your non-primitive prop values are memoized. Please provide a Code Sandbox if you need help figuring out how to do this. Here's an example https://codesandbox.io/s/react-map-gl-geocoder-using-containerref-to-ignore-events-rewdh.

**Comment by fletcherdemeo** [comment]
Hi @SamSamskies, I'm having a similar issue when rendering multiple geocoders:
- Geocoder drop down does not disappear once selection has been chosen
- Geocoder placeholder does not update to chosen selection 
- Geocoder marker is not being placed

I have attempted to memoize my non-primitive prop values and this has not changed the result, however this is the first time that I have memoized in React so not sure if done correctly. 

I have recreated these issues in Code Sandbox - https://codesandbox.io/s/multiple-react-gl-geocoders-clkps?file=/src/App.js (I've removed my mapbox token in App).

Thanks for this great project!

**Comment by SamSamskies** [comment]
Hi @fletcherdemeo, your `onResult` prop is not memoized.

**Comment by fletcherdemeo** [comment]
Thanks @SamSamskies, much appreciated?
Any idea why the first child that renders initially does not leave a marker?

**Comment by SamSamskies** [comment]
@fletcherdemeo my guess would be that it has something to do with `onResult` not being memoized.
