### ISSUE TITLE
Dopdown is disappearing after searching  the results in react-map-gl-geocoder

### ISSUE THREAD

**Issue by Maruthasalam** [SamSamskies/react-map-gl-geocoder#85]
<img width="290" alt="issues" src="https://user-images.githubusercontent.com/61966142/96418540-89773600-1210-11eb-9939-e56257da5726.PNG">
In React Map GL Gecoder Package after searching the items from input box, the results are shown in the dropdown and i select the items from the dropdwon list.the dropdwon list is hangs in there and disappering so how to over come the issues?Can please help out.
Here is my code below
<Geocoder
        mapRef={mapRef}
        onViewportChange={(e) => handleGeocoderViewportChange(e)}
        mapboxApiAccessToken={TOKEN}
        position="top-right"
      />
  const handleViewportChange = useCallback((newviewport) => {
      setviewport(newviewport)
  },[]);
  const handleGeocoderViewportChange = useCallback((viewport) => {
    const geocoderDefaultOverrides = { transitionDuration: 1000 };
    return handleViewportChange({
      ...viewport,
      ...geocoderDefaultOverrides,
    });
  },[handleViewportChange]);

**Comment by SamSamskies** [comment]
Hi @Maruthasalam. In order to avoid this, the value for `onViewportChange` needs to be memoized. In your example you are passing a new function to `onViewportChange` on every render which is causing the problem that you are having.

Try this:
```jsx
<Geocoder
    mapRef={mapRef}
    onViewportChange={handleGeocoderViewportChange}
    mapboxApiAccessToken={TOKEN}
    position="top-right"
/>
```

**Comment by utb2017** [comment]
I am having a similar problem. A). I only see one suggestion. B) The suggestion disappears when I click it. The map animates to the location. The Single suggestion then reappears. 

I can get the suggestion to disappear if I focus the Input, then click away. If I move the map, the suggestion will reappear. 

I am using nextJS, I overcame the "window is not defined", error.

I am using the container ref and the input is outside the box.

```
import { useState, useRef, forwardRef, useCallback } from 'react'
import ReactMapGL from 'react-map-gl'
import Geocoder from 'react-map-gl-geocoder'

const TOKEN = `foobar`

const Map = forwardRef(( props, ref) => {
  const state =  {
      width: '100%',
      height: '100%',
       latitude: 41.5868,
       longitude: -93.625,
      zoom: 13
  };
  const mapRef = useRef();
  const [view, setView] = useState(state);

  const handleViewportChange = useCallback((viewport) => {
    setView(viewport);
  });

    return (
      <ReactMapGL
        ref={mapRef}
        mapStyle="mapbox://styles/mapbox/streets-v9"
        mapboxApiAccessToken={TOKEN}
        onViewportChange={handleViewportChange}
        {...view}
      >
       <Geocoder
          mapRef={mapRef}
          onViewportChange={handleViewportChange}
          containerRef={ref}
          mapboxApiAccessToken={TOKEN}
          countries={'US'}
          proximity={{latitude:34.103729, longitude:-118.328613}}
          position="top-left"
        /> 

      </ReactMapGL>
    );
})

export default Map;



[Link to Example](https://firebasestorage.googleapis.com/v0/b/bronto-eff70.appspot.com/o/Logos%2FcomesBack.png?alt=media&token=83d558d2-e95d-4a03-93b4-6388f7612e98)
```

**Comment by SamSamskies** [comment]
Hi @utb2017, you're missing the deps on your useCallback. You actually don't need the useCallback in your case. And your proximity value needs to be memoized or defined outside of the function. The mapbox geocoder gets re-initialized every time a reference to a non-primitive value changes.

```js
import { useState, useRef, forwardRef, useCallback } from 'react'
import ReactMapGL from 'react-map-gl'
import Geocoder from 'react-map-gl-geocoder'

const TOKEN = `foobar`
const PROXIMITY = {latitude:34.103729, longitude:-118.328613}

const Map = forwardRef(( props, ref) => {
  const state =  {
      width: '100%',
      height: '100%',
       latitude: 41.5868,
       longitude: -93.625,
      zoom: 13
  };
  const mapRef = useRef();
  const [view, setView] = useState(state);

    return (
      <ReactMapGL
        ref={mapRef}
        mapStyle="mapbox://styles/mapbox/streets-v9"
        mapboxApiAccessToken={TOKEN}
        onViewportChange={setView}
        {...view}
      >
       <Geocoder
          mapRef={mapRef}
          onViewportChange={setView}
          containerRef={ref}
          mapboxApiAccessToken={TOKEN}
          countries={'US'}
          proximity={PROXIMITY}
          position="top-left"
        /> 

      </ReactMapGL>
    );
})

export default Map;

```

**Comment by utb2017** [comment]
@SamSamskies Thank you!!
