### ISSUE TITLE
Is it possible to change marker color?

### ISSUE THREAD

**Issue by utb2017** [SamSamskies/react-map-gl-geocoder#86]
The prop type for the marker in the `node_modules\react-map-gl-geocoder\src\index.js` is `marker: PropTypes.bool,`.

I tried this.
```            
                 const MARKER = { 'marker-color': '#3bb2d0',  'marker-size': 'large', 'marker-symbol': 'rocket' }

                 <Geocoder
                    mapRef={mapRef}
                    onViewportChange={setView}
                    containerRef={geocoderContainerRef}
                    mapboxApiAccessToken={TOKEN}
                    countries={"US"}
                    proximity={PROXIMITY}
                    position='top-left'
                    marker={MARKER}
                  />
```

I found a marker SVG in `node_modules\mapbox-gl\src\ui\marker.js`, but changing `background.setAttributeNS(null, 'fill', this._color);`  to `background.setAttributeNS(null, 'fill', '#00C805');` (and restarting application) didn't cause any changes.

Can you point me to the SVG Marker in` /node_modules` or is there another way to change the color?

```
<div
  aria-label='Map marker'
  class='mapboxgl-marker mapboxgl-marker-anchor-center'
  style='transform: translate(-50%, -50%) translate(188px, 104px) rotateX(0deg) rotateZ(0deg);'>
  <svg display='block' height='41px' width='27px' viewBox='0 0 27 41'>
    <g fill-rule='nonzero'>
      <g transform='translate(3.0, 29.0)' fill='#000000'></g>
      <g fill='#4668F2'></g>
      <g opacity='0.25' fill='#000000'></g>
      <g transform='translate(6.0, 7.0)' fill='#FFFFFF'></g>
      <g transform='translate(8.0, 8.0)'></g>
    </g>
  </svg>
</div>
```

I want to change  `<g fill='#4668F2'></g>` to `<g fill='#00C805'></g>`.

[Goal](https://firebasestorage.googleapis.com/v0/b/bronto-eff70.appspot.com/o/localhost_3001_checkout(iPhone%20X)%20(4).png?alt=media&token=8f886b32-c0e2-4607-a564-6e14370c1b2e)

**Comment by SamSamskies** [comment]
Hi @utb2017, the Marker options object documentation is here https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker. Just realized that I'm missing the link to it in the README. I'll update the README tonight. 

Here's a Code Sandbox with an example: https://codesandbox.io/s/react-map-gl-geocoder-custom-marker-aexample-bw3pb.

**Comment by utb2017** [comment]
@SamSamskies Thanks again, project complete!
