### ISSUE TITLE
In Android it's not working

### ISSUE THREAD

**Issue by debotos** [SamSamskies/react-map-gl-geocoder#89]
In IOS it's working fine but in Android(Chrome) unable to start typing.
Have a look - https://drive.google.com/file/d/1Fceyk1Gi8wVBzaSso_D6w2y8GX87aLSx/view?usp=sharing

If I came from another focused input then it works else not.

I am using version - "2.0.11"

**Comment by SamSamskies** [comment]
Hi @debotos, unfortunately I don't have an Android phone to troubleshoot. If anyone would like to tackle this issue, PRs are much appreciated. 

Did you try upgrading? I upgraded to `@mapbox/mapbox-gl-geocoder` v4.7.0 in `react-map-gl-geocoder` v2.0.14. Also, make sure that you are memoizing all non-primitive prop values besides mapRef and containerRef. The geocoder gets re-initialized if object or function prop references change between renders.

**Comment by debotos** [comment]
Hello, @SamSamskies - Thanks for the quick response.

Yes, I tried via upgrading but no luck. From default behavior perspective v2.0.11 is perfect for me. The weird thing is just a couple of months back it was working fine as far as I can remember.

Here is the implementation - 

```js
<div ref={this.geocoderSecondContainerRef} id='geoCoderSecondContainer' />
<Geocoder
  mapRef={this.mapRef}
  containerRef={this.geocoderSecondContainerRef}
  onViewportChange={this.onViewportChange}
  mapboxApiAccessToken={TOKEN}
  language={language.toLowerCase() === 'cn' ? 'zh' : language.toLowerCase()}
  inputValue={searchInputText}
  placeholder={`${translate(website, 'textLanguageList', 'search-city', language)}`}
  onResult={(e: any) => {
    const { place_name, center } = e.result
    console.log('Searching jobs in coords: ', center)
    if (this._mounted) {
      this.setState({ searchInputText: place_name })
    }
    this._searchJobsAroundCoords(center)
  }}
/>
```

**Comment by debotos** [comment]
Hey @SamSamskies - You're right! 
It was happening because of re-render. After I isolated the component everything is back to normal.

Here is the implementation - 

```js
/* eslint-disable react/display-name */
import React from 'react'
import { Spin } from 'antd'
import dynamic from 'next/dynamic'

import keys from '@config/keys'
import { translate } from '@utils/translationHelper'

/* Module only avail only client side because they depend on 'window' */
const Geocoder: any = dynamic(() => import('react-map-gl-geocoder'), {
  ssr: false,
  loading: () => <Spin size='small' />,
})

const { TOKEN } = keys

function MapGeocoder({ mapRef, containerRef, onViewportChange, language, inputValue, website, onResult }: any) {
  return (
    <Geocoder
      mapRef={mapRef}
      containerRef={containerRef}
      onViewportChange={onViewportChange}
      mapboxApiAccessToken={TOKEN}
      language={language.toLowerCase() === 'cn' ? 'zh' : language.toLowerCase()}
      inputValue={inputValue}
      placeholder={`${translate(website, 'textLanguageList', 'search-city', language)}`}
      onResult={({ result }: any) => {
        const { place_name, center } = result
        console.log('Searching jobs in coords: ', center)
        onResult(place_name, center)
      }}
      onError={({ error }: any) => console.log(error)}
    />
  )
}

export default React.memo(MapGeocoder, (prevProps: any, nextProps: any) => {
  const { inputValue: prevInputValue } = prevProps
  const { inputValue: nextInputValue } = nextProps
  // console.log({ prevInputValue, nextInputValue })

  const inputValueIsSame = prevInputValue === nextInputValue

  const propsAreSame = inputValueIsSame
  // true -> props are equal
  // false -> props are not equal -> update the component
  if (!propsAreSame) {
    console.log('Re-rendering Geocoder!')
  }

  return propsAreSame
})
```

**Comment by SamSamskies** [comment]
Another solution would be to memoize the `onResult` and `onError` prop values. The Geocoder component is a Pure Component, so as long as none of the references change, it won't re-initialize the geocoder. This trips a lot of people up. Even tripped myself up once 😂. One of these days I plan to sit down and re-architect this component to get rid of this constraint.
