### ISSUE TITLE
On result handler

### ISSUE THREAD

**Issue by sos0** [SamSamskies/react-map-gl-geocoder#9]
Hello,

Separate question from my other one (#8), how do I add a onResults or onResult handler to the component?

**Comment by SamSamskies** [comment]
There's not an easy way to do this right now. I'll try and work on adding the ability to pass these in as props this weekend.

**Comment by sos0** [comment]
Thanks so much!

**Comment by SamSamskies** [comment]
I added props for onResults and onResult in the latest version. README is updated with all available props. Let me know if you have any problems.

**Comment by sos0** [comment]
Am I correct in understanding that all I have to do is pass a function to the `onResult` prop to achieve the same result as [this example](https://www.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/)?

I tried this and nothing got printed after searching + selecting a result:
```jsx
_onGeocoderResult = (results) => {
  console.log(results);
}
// ... a bunch of code and ReactMapGL wrapper 
<Geocoder mapRef={this.mapRef}
  onResult={this._onGeocoderResult}
  onViewportChange={this._handleGeocoderViewportChange}
  mapboxApiAccessToken={config.MAPBOX_PUBLIC_TOKEN} />
```

**Comment by SamSamskies** [comment]
That should work. Could you verify that you're using v1.4.5?

See example here: https://codesandbox.io/s/0vpoxn0n9l

I just noticed there's an existing bug with mapbox-gl-geocoder that causes onResult to fire twice. https://github.com/mapbox/mapbox-gl-geocoder/issues/99.

**Comment by sos0** [comment]
I'll try removing my dependencies and re-updating!

**Comment by SamSamskies** [comment]
Does the example work for you? If it doesn't, let me know what your search query is.

**Comment by sos0** [comment]
It worked! I just had to remove my node_modules folder and reinstall. :) Thanks so much Sam!

**Comment by SamSamskies** [comment]
No problem. Let me know if that bug causing the event to fire twice is a problem for you. I can try and help them fix the bug or figure out a workaround if it is.
