### ISSUE TITLE
CORS error when searching.

### ISSUE THREAD

**Issue by kelvin0712** [SamSamskies/react-map-gl-geocoder#93]
**Reproduce**
When we try to search for any address, CORS errors will appear in the log. 
In the picture below, I used the example from https://codesandbox.io/s/l7p179qr6m
<img width="699" alt="Screen Shot 2020-12-09 at 4 41 39 pm" src="https://user-images.githubusercontent.com/45527642/101589927-809b2780-3a3d-11eb-896b-3a67bdcd97b5.png">

**Comment by SamSamskies** [comment]
Hi @kelvin0712, can you provide a sandbox that reproduces this problem? Also, this doesn't seem like it would be a problem with `react-map-gl-geocoder`. You can try removing the geocoder to verify. Please close this issue if you verify that it's not a problem with `react-map-gl-geocoder`.
