### ISSUE TITLE
Menu stays open

### ISSUE THREAD

**Issue by carolineleger** [SamSamskies/react-map-gl-geocoder#96]
Hi,

I'm having the exact same issue as this one:
https://github.com/SamSamskies/react-map-gl-geocoder/issues/81
With the menu reopening after searching, except that i'm not using bbox. 

My geocoder search field is outside my map component, I also tried to put it in the same component, but with same results.
Any idea?

Thanks!

const Map = (props) => {
  const mapRef = useRef();
  
  const handleViewportChange = (view) => {
    props.updateMap({...props.map, ...view})
  }

  const handleGeocoderViewportChange = (viewport) => {
    const geocoderDefaultOverrides = { transitionDuration: 2000 };

    return handleViewportChange({
      ...viewport,
      ...geocoderDefaultOverrides
    });
  };

  return (
    <div className="map">
      <MapGL
        ref={mapRef}
        {...props.map}
        width="100%"
        height="100%"
        onViewportChange={handleViewportChange}
        mapboxApiAccessToken={mapboxToken}
        mapStyle='mapbox://styles/mapbox/streets-v11'
      >
        <div className="map__nav">
          <NavigationControl />
        </div>

        <Geocoder
          mapRef={mapRef}
          containerRef={geocoderContainerRef}
          onViewportChange={handleGeocoderViewportChange}
          mapboxApiAccessToken={mapboxToken}
        />
      </MapGL>
    </div>
  )
}

**Comment by SamSamskies** [comment]
Hi @carolineleger, any props that are functions or objects need to be memoized to prevent this from happening. In your case you need to memoize your `handleGeocoderViewportChange` function. For more info check out issue #84.

**Comment by carolineleger** [comment]
@SamSamskies Thanks, that helped :)
